[tool.commitizen]
name = "cz_customize"

[tool.commitizen.customize]
message_template = "{{commit_msg}}{% if ticket_number != \"none\" %} (quadproduction/issues#{{ticket_number}}){% endif %}"
example = "Commit message (quadproduction/issues#123)"
schema = "<commit_msg> (quadproduction/issues#<ticket_number>)"
schema_pattern = ".*( \\(quadproduction/issues#\\d+\\))?$"

[[tool.commitizen.customize.questions]]
type = "input"
name = "ticket_number"
message = "Ticket number: "

[[tool.commitizen.customize.questions]]
type = "input"
name = "commit_msg"
message = "Commit message: "
