repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
    - id: no-commit-to-branch
      args: [ '--pattern', '^(?!((release|enhancement|feature|bugfix|hotfix|documentation|tests|local|chore)\/[\w_.-]+)$).*' ]
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.12.0
    hooks:
    - id: commitizen
      name: commitizen check
      description: >
        Check whether the current commit message follows commiting rules. Allow
        empty commit messages by default, because they typically indicate to Git
        that the commit should be aborted.
      entry: cz check
      args: [ --allow-abort, --commit-msg-file ]
      stages: [ commit-msg ]
      language: python
      language_version: python3