BACKDROP_FONT_SIZE = 75
MAIN_BACKDROP_PADDING = 15

NODES_IN_BACKDROP_X_PADDING = 40
NODES_IN_BACKDROP_Y_PADDING = 150
NODES_IN_PUBLISH_X_PADDING = 115
NODES_IN_PUBLISH_Y_PADDING = 225
BACKDROP_W_PADDING = 80
BACKDROP_H_PADDING = 200
BACKDROP_PUBLISH_W_PADDING = 230
BACKDROP_PUBLISH_H_PADDING = 350

BACKDROP_INSIDE_W_PADDING = 100
BACKDROP_INSIDE_H_PADDING = 200

BACKDROP_INSIDE_X_PADDING = 40
BACKDROP_INSIDE_Y_PADDING = 150

NODE_DEFAULT_WIDTH = 50

LOAD_BACKDROP = "Pipe Load Backdrop"
LOAD_RENDERLAYER_BACKDROP = "Pipe Load RenderLayer Backdrop"
PUBLISH_BACKDROP = "Pipe Publish Backdrop"
MAIN_BACKDROP = "Pipe Main Backdrop"
PARENT_BACKDROP = "Pipe Parent Backdrop"
LINKED_READ = "Linked to representation"
DEFAULT_BACKDROP_SIZE = "50x50"

PSD_EXT = ["psd", "psb"]
EXR_EXT = ["exr"]

DEFAULT_ANCHOR_TAGS = "2D,"
DEFAULT_ANCHOR_TYPE = "2D"
DEFAULT_STAMP_TAGS = ["2D"]

RGBA = "rgba"

DECOMPOSE_LAYER_PADDING = 35
SHUFFLE_X_PADDING = 110
SHUFFLE_Y_PADDING = 122
REMOVE_Y_PADDING = 25
PREMULT_Y_PADDING = 25
DOT_X_PADDING = 35
DOT_Y_PADDING = 70
ANCHOR_Y_PADDING = 100
ANCHOR_DOT_X_OFFSET = 34
STAMP_Y_PADDING = 25

DOT_X_ALIGN_OFFSET = 34
ANCHOR_Y_ALIGN_OFFSET = 118
